"""
rlai_mapping/launch/map_server.launch.py

Serve a pre-built occupancy map WITHOUT starting a new SLAM session.

Use this when the environment has already been mapped and you want to:
  • Run AMCL localisation against a known map
  • Visualise the saved map in RViz2
  • Provide the /map topic to nav2 navigation without re-mapping

Starts:
  1. map_server  (nav2_map_server lifecycle node)
     — loads the occupancy grid from map_yaml_file onto /map
  2. lifecycle_manager
     — auto-configures and activates map_server

Usage:
  ros2 launch rlai_mapping map_server.launch.py \\
    map_yaml_file:=/home/user/maps/warehouse.yaml

  ros2 launch rlai_mapping map_server.launch.py \\
    map_yaml_file:=/home/user/maps/warehouse.yaml \\
    use_sim_time:=true

After launch, the map is available on:
  /map  (nav_msgs/OccupancyGrid)

To also run localisation (AMCL) against this map, use:
  ros2 launch rlai_localization localization_amcl.launch.py \\
    map_yaml_file:=/home/user/maps/warehouse.yaml
"""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    pkg = FindPackageShare('rlai_mapping')

    map_server_yaml = PathJoinSubstitution([pkg, 'config', 'map_server.yaml'])

    # ── Launch arguments ──────────────────────────────────────────────────
    declared_args = [
        DeclareLaunchArgument(
            'use_sim_time',
            default_value='true',
            description='Use simulation (Gazebo) clock',
        ),
        DeclareLaunchArgument(
            'map_yaml_file',
            description=(
                'Absolute path to the occupancy-grid YAML file to serve. '
                'Generated by nav2_map_server map_saver_cli or slam_toolbox SaveMap.'
            ),
        ),
    ]

    # ── map_server (lifecycle node) ───────────────────────────────────────
    # Reads the YAML file, publishes nav_msgs/OccupancyGrid on /map.
    map_server_node = Node(
        package='nav2_map_server',
        executable='map_server',
        name='map_server',
        output='screen',
        parameters=[
            map_server_yaml,
            {
                'use_sim_time': LaunchConfiguration('use_sim_time'),
                # Override the yaml_filename from the YAML config with the
                # launch argument so the map path can be supplied at runtime.
                'yaml_filename': LaunchConfiguration('map_yaml_file'),
            },
        ],
    )

    # ── lifecycle_manager ─────────────────────────────────────────────────
    # Drives map_server through configure → active so it starts publishing.
    lifecycle_manager = Node(
        package='nav2_lifecycle_manager',
        executable='lifecycle_manager',
        name='lifecycle_manager_map_server',
        output='screen',
        parameters=[{
            'use_sim_time': LaunchConfiguration('use_sim_time'),
            'autostart': True,
            'node_names': ['map_server'],
        }],
    )

    return LaunchDescription(
        declared_args + [
            map_server_node,
            lifecycle_manager,
        ]
    )
